In [53]:
import numpy as np
# import pandas as pd
import xarray as xr
from pathlib import Path

from esdglider import gcp, paths, utils

deployment_name = "capex987-20260128"
mode = "delayed"

### Consistent variables
# Define directories - KB edits commentted out gcs paths for local paths
# home = Path.home()
# mnt_path = home / "gcs-mnt"
# cac_path = home / "standard-glider-files" / "Cache"
# config_path = home / "glider-lab" / "deployment-configs"

home = Path("D:/esd data structure/")
# mnt_path = home / "gcs-mnt"
cac_path = "D:/esd data structure/cache/"
config_path = "deployment-configs/"

# Bucket names and paths
# data_in_bucket_name = "swfscesd-glider-deployments-data-in"
# data_out_bucket_name = "swfscesd-glider-deployments-data-out"
data_in_bucket_name = "D:/esd data structure/data-in"
data_out_bucket_name = "D:/esd data structure/data-out"

# data_in_path = mnt_path / data_in_bucket_name
# data_out_path = mnt_path / data_out_bucket_name
data_in_path = Path(data_in_bucket_name)
data_out_path = Path(data_out_bucket_name)

glider_paths = paths.get_path_glider(
    deployment_name = deployment_name, 
    mode = mode, 
    config_path = "C:/Users/kourtney.burger/Documents/GitHub/glider-lab/deployment-configs", 
    data_in_path = data_in_path, 
    data_out_path = data_out_path, 
    cac_path = cac_path, 
)

### Mount the relevant bucket(s)
# gcp.gcs_mount_bucket(data_out_bucket_name, data_out_path, ro=True)

In [54]:
ds_raw = xr.load_dataset(glider_paths["tsrawpath"])
df_raw = ds_raw.to_pandas()
display(ds_raw)

<xarray.Dataset> Size: 466MB
Dimensions:                   (time: 1492863)
Coordinates:
  * time                      (time) datetime64[ns] 12MB 2026-01-29T03:45:00....
    latitude                  (time) float64 12MB nan nan nan ... nan nan nan
    longitude                 (time) float64 12MB nan nan nan ... nan nan nan
Data variables: (12/32)
    depth_measured            (time) float64 12MB nan 0.0217 nan ... nan nan nan
    depth_ctd                 (time) float64 12MB 0.03548 nan ... nan nan
    profile_index             (time) float64 12MB 0.5 0.5 0.5 ... 229.5 229.5
    profile_direction         (time) float64 12MB nan 1.0 1.0 ... nan nan nan
    conductivity              (time) float64 12MB 5.375 nan 5.375 ... nan nan
    temperature               (time) float64 12MB 25.34 nan 25.34 ... nan nan
    ...                        ...
    target_depth              (time) float64 12MB nan nan nan ... nan nan nan
    waypoint_latitude         (time) float64 12MB nan nan nan ... nan nan nan
    waypoint_longitude        (time) float64 12MB nan nan nan ... nan nan nan
    distance_over_ground      (time) float64 12MB nan nan nan ... nan nan nan
    source_filename           (time) <U12 72MB '07840000.ebd' ... '07990004.ebd'
    trajectory                <U17 68B 'capex987-20260128'
Attributes: (12/59)
    Conventions:               CF-1.8
    Metadata_Conventions:      Unidata Dataset Discovery v1.0, COARDS, CF-1.8
    acknowledgment:            This work was supported by funding from NOAA. ...
    cdm_data_type:             Trajectory
    comment:                   Underwater Glider Challange 2026 (aka Glider R...
    contributor_name:          Kourtney Burger
    ...                        ...
    summary:                   These data are part of the NOAA Fisheries 2026...
    time_coverage_end:         20260212T191733
    time_coverage_start:       20260129T034500
    title:                     capex987-20260129T0345
    transmission_system:       IRIDIUM
    wmo_id:

In [55]:
ds_eng = xr.load_dataset(glider_paths["tsengpath"])
df_eng = ds_eng.to_pandas()
display(ds_eng)

ds_sci = xr.load_dataset(glider_paths["tsscipath"])
df_sci = ds_sci.to_pandas()
display(ds_sci)

<xarray.Dataset> Size: 63MB
Dimensions:               (time: 288538)
Coordinates:
  * time                  (time) datetime64[ns] 2MB 2026-01-29T03:45:01.10400...
    depth                 (time) float64 2MB 0.0217 0.0218 ... 0.0391 0.0144
    latitude              (time) float64 2MB 21.2 21.19 21.19 ... 21.36 21.36
    longitude             (time) float64 2MB -158.1 -158.1 ... -158.2 -158.2
Data variables: (12/16)
    profile_index         (time) float64 2MB 0.5 0.5 0.5 ... 229.5 229.5 229.5
    profile_direction     (time) float64 2MB 1.0 -1.0 1.0 1.0 ... -1.0 -1.0 nan
    heading               (time) float64 2MB 1.71 2.064 2.357 ... nan nan nan
    pitch                 (time) float64 2MB 0.403 0.2452 0.1144 ... nan nan nan
    roll                  (time) float64 2MB 0.01762 0.0186 0.01941 ... nan nan
    battery_voltage       (time) float64 2MB 16.19 16.19 16.19 ... 14.23 14.23
    ...                    ...
    leak_detect           (time) float64 2MB 2.498 2.494 2.492 ... 2.494 2.496
    leak_detect_forward   (time) float64 2MB 2.49 2.486 2.483 ... 2.486 2.488
    leak_detect_science   (time) float64 2MB 2.491 2.487 2.484 ... 2.487 2.489
    vacuum                (time) float64 2MB 8.855 8.295 7.832 ... 7.933 8.139
    distance_over_ground  (time) float64 2MB 0.0 0.728 1.094 ... 376.8 376.9
    trajectory            (time) <U17 20MB 'capex987-20260128' ... 'capex987-...
Attributes: (12/59)
    Conventions:               CF-1.8
    Metadata_Conventions:      Unidata Dataset Discovery v1.0, COARDS, CF-1.8
    acknowledgment:            This work was supported by funding from NOAA. ...
    cdm_data_type:             Trajectory
    comment:                   Underwater Glider Challange 2026 (aka Glider R...
    contributor_name:          Kourtney Burger
    ...                        ...
    summary:                   These data are part of the NOAA Fisheries 2026...
    time_coverage_end:         20260212T191021
    time_coverage_start:       20260129T034501
    title:                     capex987-20260129T0345
    transmission_system:       IRIDIUM
    wmo_id:

<xarray.Dataset> Size: 254MB
Dimensions:                   (time: 1156352)
Coordinates:
  * time                      (time) datetime64[ns] 9MB 2026-01-29T03:45:00.6...
    latitude                  (time) float64 9MB 21.2 21.2 21.2 ... 21.36 21.36
    longitude                 (time) float64 9MB -158.1 -158.1 ... -158.2 -158.2
    depth                     (time) float64 9MB 0.03548 -0.0009938 ... 0.03886
Data variables: (12/16)
    profile_index             (time) float64 9MB 0.5 0.5 0.5 ... 229.5 229.5
    profile_direction         (time) float64 9MB -1.0 1.0 -1.0 ... -1.0 -1.0 nan
    conductivity              (time) float64 9MB 5.375 5.375 ... 5.327 5.327
    temperature               (time) float64 9MB 25.34 25.34 25.34 ... 25.0 25.0
    pressure                  (time) float64 9MB 0.0357 -0.001 ... 0.042 0.0391
    salinity                  (time) float64 9MB 35.23 35.23 ... 35.15 35.15
    ...                        ...
    pitch                     (time) float64 9MB 0.4061 0.3995 ... nan nan
    roll                      (time) float64 9MB 0.0176 0.01764 ... nan nan
    water_velocity_eastward   (time) float64 9MB -0.3733 -0.3731 ... nan nan
    water_velocity_northward  (time) float64 9MB -0.01254 -0.01268 ... nan nan
    distance_over_ground      (time) float64 9MB 0.0 0.03032 ... 376.7 376.7
    trajectory                (time) <U17 79MB 'capex987-20260128' ... 'capex...
Attributes: (12/59)
    Conventions:               CF-1.8
    Metadata_Conventions:      Unidata Dataset Discovery v1.0, COARDS, CF-1.8
    acknowledgment:            This work was supported by funding from NOAA. ...
    cdm_data_type:             Trajectory
    comment:                   Underwater Glider Challange 2026 (aka Glider R...
    contributor_name:          Kourtney Burger
    ...                        ...
    summary:                   These data are part of the NOAA Fisheries 2026...
    time_coverage_end:         20260212T191004
    time_coverage_start:       20260129T034500
    title:                     capex987-20260129T0345
    transmission_system:       IRIDIUM
    wmo_id:

## Profile checks

In [56]:
# print("-------ENG")
# display(utils.check_profiles(utils.calc_profile_summary(ds_eng, "depth")))
# print("-------SCI")
# display(utils.check_profiles(utils.calc_profile_summary(ds_sci, "depth")))

print("-------RAW")
prof_summ_raw = utils.calc_profile_summary(ds_raw, "depth_measured")
utils.check_profiles(prof_summ_raw)
print(f"Dives: {np.count_nonzero(prof_summ_raw.profile_direction.values == 1)}")
print(f"Climbs: {np.count_nonzero(prof_summ_raw.profile_direction.values == -1)}")
display(prof_summ_raw)

-------RAW

There are different numbers of dives and climbs: dives: 115; climbs: 114
(OPT) The following 1 dives are not 2-followed by a climb: 133.0
There are 3 profiles with more than 180s at depths less than or equal to 5m. Profile indices: 94.0, 147.0, 163.0

Dives: 115
Climbs: 114

,profile_index,profile_direction,profile_phase,start_time,end_time,start_depth,end_depth,min_depth,max_depth,depth_range,min_lon,max_lon,min_lat,max_lat,distance_traveled,num_points,time_at_surface_s,profile_duration_s
0,0.5,0.0,surfacing,2026-01-29 03:45:00.644999936,2026-01-29 03:46:13.036000000,0.021700,0.073100,0.020200,0.136900,0.116700,-158.135897,-158.135840,21.189373,21.189418,NaN,92,71,72.391
1,1.0,1.0,descent,2026-01-29 03:46:14.002000128,2026-01-29 03:51:57.022000128,0.078700,55.964199,0.078700,55.964199,55.885499,-158.136071,-158.135730,21.188908,21.189352,NaN,429,44,343.020
2,1.5,0.0,inflection,2026-01-29 03:51:57.520000000,2026-01-29 03:52:17.540999936,55.970699,55.863201,55.857498,55.970699,0.113201,-158.136154,-158.136085,21.188928,21.188937,NaN,26,0,20.021
3,2.0,-1.0,ascent,2026-01-29 03:52:18.022000128,2026-01-29 03:59:05.083000064,55.853199,1.212800,1.212800,55.853199,54.640399,-158.136429,-158.136168,21.188939,21.189050,NaN,508,44,407.061
4,2.5,0.0,surfacing,2026-01-29 03:59:05.280999936,2026-01-29 04:11:57.848999936,0.018200,0.079600,0.000000,0.089800,0.089800,-158.134102,-158.132898,21.185998,21.187280,NaN,700,772,772.568
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
454,227.5,0.0,surfacing,2026-02-12 18:50:26.298000128,2026-02-12 19:00:55.024000000,2.547100,0.131000,0.033200,2.660600,2.627400,-158.150242,-158.150105,21.353517,21.354432,NaN,510,628,628.726
455,228.0,1.0,descent,2026-02-12 19:00:56.003000064,2026-02-12 19:04:32.039000064,0.175300,23.865000,0.175300,23.865000,23.689700,-158.150245,-158.150162,21.354418,21.354914,NaN,270,52,216.036
456,228.5,0.0,inflection,2026-02-12 19:04:32.423000064,2026-02-12 19:04:32.423000064,23.888100,23.888100,23.888100,23.888100,0.000000,-158.150158,-158.150158,21.354918,21.354918,0.0,1,0,0.000
457,229.0,-1.0,ascent,2026-02-12 19:04:33.039000064,2026-02-12 19:07:53.063000064,23.830200,2.809500,2.809500,23.830200,21.020700,-158.150290,-158.150153,21.354922,21.355071,NaN,249,12,200.024
458,229.5,0.0,surfacing,2026-02-12 19:07:53.530999808,2026-02-12 19:17:33.403000064,2.662900,0.072500,0.014400,2.845400,2.831000,-158.150372,-158.150333,21.355382,21.355480,NaN,523,557,579.872

In [57]:
d = ds_sci.where(ds_sci.pressure.isnull(), drop = True)
d

<xarray.Dataset> Size: 0B
Dimensions:                   (time: 0)
Coordinates:
  * time                      (time) datetime64[ns] 0B
    latitude                  (time) float64 0B
    longitude                 (time) float64 0B
    depth                     (time) float64 0B
Data variables: (12/16)
    profile_index             (time) float64 0B
    profile_direction         (time) float64 0B
    conductivity              (time) float64 0B
    temperature               (time) float64 0B
    pressure                  (time) float64 0B
    salinity                  (time) float64 0B
    ...                        ...
    pitch                     (time) float64 0B
    roll                      (time) float64 0B
    water_velocity_eastward   (time) float64 0B
    water_velocity_northward  (time) float64 0B
    distance_over_ground      (time) float64 0B
    trajectory                (time) object 0B
Attributes: (12/59)
    Conventions:               CF-1.8
    Metadata_Conventions:      Unidata Dataset Discovery v1.0, COARDS, CF-1.8
    acknowledgment:            This work was supported by funding from NOAA. ...
    cdm_data_type:             Trajectory
    comment:                   Underwater Glider Challange 2026 (aka Glider R...
    contributor_name:          Kourtney Burger
    ...                        ...
    summary:                   These data are part of the NOAA Fisheries 2026...
    time_coverage_end:         20260212T191004
    time_coverage_start:       20260129T034500
    title:                     capex987-20260129T0345
    transmission_system:       IRIDIUM
    wmo_id:

In [58]:
# idx_list = 6.5, 8.5, 10.5, 14.5, 18.5, 22.5, 30.5, 34.5, 38.5, 58.5, 74.5, 78.5, 82.5, 86.5, 98.5, 118.5, 122.5, 142.5, 166.5, 174.5, 182.5, 190.5, 194.5, 210.5, 218.5, 222.5, 230.5, 242.5, 250.5, 282.5, 294.5, 306.5, 334.5, 358.5, 370.5, 374.5, 410.5, 424.5, 430.5, 438.5, 442.5, 478.5, 494.5, 498.5, 518.5, 526.5, 530.5, 534.5, 538.5, 550.5, 554.5, 558.5, 566.5, 582.5, 594.5, 602.5, 618.5, 630.5, 646.5, 654.5, 666.5, 670.5, 674.5, 678.5, 690.5, 694.5, 702.5, 706.5, 710.5, 714.5, 722.5, 746.5, 750.5, 754.5, 762.5, 766.5, 770.5
# p1 = utils.check_profiles(ds_sci)
# p1e = p1[np.isin(p1["profile_index"], idx_list)]
# p1e

# ds = ds_raw
# dt = "2023-12-19"
# ds_sub1 = ds.sel(time=slice(f"{dt} 08:00", dt))
# ds_sub1

## Exploring new profile calculations

In [59]:
ds_touse = ds_raw.copy(deep=True)

# vars_keep = ["longitude", "latitude", "depth_measured", #"depth_ctd", 
#                 "profile_index", "profile_direction"]
vars_keep = ["depth_measured", #"depth_ctd", 
                "profile_index", "profile_direction"]

x_orig = utils.data_var_reorder(ds_touse, vars_keep)
# regions_df_orig = utils.calc_regions(x_orig)
# print(x_orig.profile_index.attrs)

# utils.profileOptionsList #findProf defaults

# pgutils.get_profiles_new(x, filt_time=20)
p1, p2, p_opt = utils.findProfiles(
    x_orig.time.values,
    x_orig.depth_measured.values,
    # stall=50, 
    # shake=15,
    # interrupt=300,
    # inversion=10,
    length=12,
    # period=0,
)
# # Defaults    
# stall=3, #scalar with the maximum vertical displacement when stalled.
# shake=20, #scalar with the maximum duration of a vertical shake.
# interrupt=180, #scalar with the maximum duration of stalled and/or shake intervals during a cast.
# inversion=3, #scalar with the maximum depth inversion allowed during a cast.
# length=10, #scalar with the minimum depth range a cast must span.
# period=0, #scalar with the minimum duration range a cast must last.

orig = ["profile_index_orig", "profile_direction_orig"]
x = x_orig.rename_vars({"profile_index": orig[0], "profile_direction": orig[1]})
x["profile_index"] = ('time', p1, {})
x["profile_direction"] = ('time', p2, {})
x = utils.data_var_reorder(x, (vars_keep + orig))

# x["dives"] = ('time', gt.utils.calc_dive_number(x.time.values, x.depth.values, dive_depth_threshold=15), {})
# display(x)

ds = x
dt = "2026-02-09"
ds_sub = ds.sel(time=slice(f"{dt} 07:13", dt))
df_sub = ds_sub.to_pandas()
ds_sub

<xarray.Dataset> Size: 24MB
Dimensions:                   (time: 72548)
Coordinates:
  * time                      (time) datetime64[ns] 580kB 2026-02-09T07:13:00...
    latitude                  (time) float64 580kB nan nan 21.38 ... nan 21.31
    longitude                 (time) float64 580kB nan nan -158.3 ... nan -158.2
Data variables: (12/34)
    depth_measured            (time) float64 580kB nan nan 950.6 ... nan 58.89
    profile_index             (time) float64 580kB 161.0 161.0 ... 170.0 170.0
    profile_direction         (time) float64 580kB 1.0 1.0 -1.0 ... -1.0 -1.0
    profile_index_orig        (time) float64 580kB 162.0 162.0 ... 171.0 171.0
    profile_direction_orig    (time) float64 580kB 1.0 1.0 -1.0 ... -1.0 -1.0
    depth_ctd                 (time) float64 580kB 942.5 942.6 nan ... 59.04 nan
    ...                        ...
    target_depth              (time) float64 580kB nan nan nan ... nan nan nan
    waypoint_latitude         (time) float64 580kB nan nan nan ... nan nan nan
    waypoint_longitude        (time) float64 580kB nan nan nan ... nan nan nan
    distance_over_ground      (time) float64 580kB nan nan 274.9 ... nan 290.5
    source_filename           (time) <U12 3MB '07970006.ebd' ... '07970015.dbd'
    trajectory                <U17 68B 'capex987-20260128'
Attributes: (12/59)
    Conventions:               CF-1.8
    Metadata_Conventions:      Unidata Dataset Discovery v1.0, COARDS, CF-1.8
    acknowledgment:            This work was supported by funding from NOAA. ...
    cdm_data_type:             Trajectory
    comment:                   Underwater Glider Challange 2026 (aka Glider R...
    contributor_name:          Kourtney Burger
    ...                        ...
    summary:                   These data are part of the NOAA Fisheries 2026...
    time_coverage_end:         20260212T191733
    time_coverage_start:       20260129T034500
    title:                     capex987-20260129T0345
    transmission_system:       IRIDIUM
    wmo_id:

In [63]:
# Implement specific checks, if needed, -8 for all after correction based on start of mission
# 141 correction
x["profile_index"].loc[
    dict(time=slice("2026-02-06 22:00", "2026-02-06 22:30:45"))
] = 133

# # 102 correction
x["profile_index"].loc[
    dict(time=slice("2026-02-03 13:01:33", "2026-02-03 13:32:00"))
] = 94.5

# 155 correction
x["profile_index"].loc[
    dict(time=slice("2026-02-07 22:35", "2026-02-07 22:36:45"))
] = 146.5

# 171 correction 
x["profile_index"].loc[
    dict(time=slice("2026-02-09 09:41", "2026-02-09 09:43"))
] = 162.5

In [64]:
# Check profiles
prof_summ = utils.calc_profile_summary(x, "depth_measured")
utils.check_profiles(prof_summ)
print(f"Dives: {np.count_nonzero(prof_summ.profile_direction.values == 1)}")
print(f"Climbs: {np.count_nonzero(prof_summ.profile_direction.values == -1)}")

# gg = prof_summ[prof_summ.profile_index.isin([6.5, 10.5, 14.5, 18.5, 26.5, 30.5, 50.5, 62.5, 70.5, 78.5, 110.5, 114.5, 158.5, 210.5, 218.5, 222.5, 270.5, 274.5, 346.5, 350.5, 362.5, 430.5, 440.5, 478.5, 482.5, 490.5, 494.5, 510.5, 562.5, 594.5, 602.5, 646.5, 666.5, 702.5, 714.5, 738.5, 764.5, 770.5])]
# display(gg)

prof_summ

Dives: 114
Climbs: 114

,profile_index,profile_direction,profile_phase,start_time,end_time,start_depth,end_depth,min_depth,max_depth,depth_range,min_lon,max_lon,min_lat,max_lat,distance_traveled,num_points,time_at_surface_s,profile_duration_s
0,0.5,0.0,surfacing,2026-01-29 03:45:00.644999936,2026-01-29 03:46:13.036000000,0.021700,0.073100,0.020200,0.136900,0.116700,-158.135897,-158.135840,21.189373,21.189418,NaN,92,71,72.391
1,1.0,1.0,descent,2026-01-29 03:46:14.002000128,2026-01-29 03:51:57.022000128,0.078700,55.964199,0.078700,55.964199,55.885499,-158.136071,-158.135730,21.188908,21.189352,NaN,429,44,343.020
2,1.5,0.0,inflection,2026-01-29 03:51:57.520000000,2026-01-29 03:52:17.540999936,55.970699,55.863201,55.857498,55.970699,0.113201,-158.136154,-158.136085,21.188928,21.188937,NaN,26,0,20.021
3,2.0,-1.0,ascent,2026-01-29 03:52:18.022000128,2026-01-29 03:59:05.083000064,55.853199,1.212800,1.212800,55.853199,54.640399,-158.136429,-158.136168,21.188939,21.189050,NaN,508,44,407.061
4,2.5,0.0,surfacing,2026-01-29 03:59:05.280999936,2026-01-29 04:11:57.848999936,0.018200,0.079600,0.000000,0.089800,0.089800,-158.134102,-158.132898,21.185998,21.187280,NaN,700,772,772.568
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
452,226.5,0.0,surfacing,2026-02-12 18:50:26.298000128,2026-02-12 19:00:55.024000000,2.547100,0.131000,0.033200,2.660600,2.627400,-158.150242,-158.150105,21.353517,21.354432,NaN,510,628,628.726
453,227.0,1.0,descent,2026-02-12 19:00:56.003000064,2026-02-12 19:04:32.039000064,0.175300,23.865000,0.175300,23.865000,23.689700,-158.150245,-158.150162,21.354418,21.354914,NaN,270,52,216.036
454,227.5,0.0,inflection,2026-02-12 19:04:32.423000064,2026-02-12 19:04:32.423000064,23.888100,23.888100,23.888100,23.888100,0.000000,-158.150158,-158.150158,21.354918,21.354918,0.0,1,0,0.000
455,228.0,-1.0,ascent,2026-02-12 19:04:33.039000064,2026-02-12 19:07:53.063000064,23.830200,2.809500,2.809500,23.830200,21.020700,-158.150290,-158.150153,21.354922,21.355071,NaN,249,12,200.024
456,228.5,0.0,surfacing,2026-02-12 19:07:53.530999808,2026-02-12 19:17:33.403000064,2.662900,0.072500,0.014400,2.845400,2.831000,-158.150372,-158.150333,21.355382,21.355480,NaN,523,557,579.872

In [ ]:
# Check profiles on eng and sci datasets
print("ENG------")
x_eng = utils.join_profiles(ds_eng, prof_summ)
prof_summ_eng = utils.calc_profile_summary(x_eng, "depth")
display(utils.check_profiles(prof_summ_eng))

print("SCI------")
x_sci = utils.join_profiles(ds_sci, prof_summ)
prof_summ_sci = utils.calc_profile_summary(x_sci, "depth")
display(utils.check_profiles(prof_summ_sci))

In [ ]:
# regions_df_orig = utils.calc_regions(x_orig)
# regions_df = utils.calc_regions(x)
# # display(regions_df)
# # print(np.argwhere(regions_df_orig.profile_description == np.roll(regions_df_orig.profile_description, 1)))

# # print(regions_df["profile_direction"].value_counts())
# print("------------")
# print(f"Climbs orig: {np.count_nonzero(regions_df_orig["profile_direction"] == -1)}")
# print(f"Dives orig: {np.count_nonzero(regions_df_orig["profile_direction"] == 1)}")
# utils.check_profiles(x_orig)

# print("------------")
# print(f"Climbs: {np.count_nonzero(regions_df["profile_direction"] == -1)}")
# print(f"Dives: {np.count_nonzero(regions_df["profile_direction"] == 1)}")
# utils.check_profiles(x)

# regions_df
# regions_df_orig
# 
# 
# prof_summ_df_orig = utils.check_profiles(x_orig)
# prof_summ_df = utils.check_profiles(x)

# between_df_orig = prof_summ_df_orig[prof_summ_df_orig["profile_index"] % 1 == 0.5]
# between_df = prof_summ_df[prof_summ_df["profile_index"] % 1 == 0.5]

# # print((between_df_orig.end_time - between_df_orig.start_time).describe())
# # print((between_df.end_time - between_df.start_time).describe())

# print(abs(between_df_orig.end_depth - between_df_orig.start_depth).describe())
# print(abs(between_df.end_depth - between_df.start_depth).describe())

# prof_summ_df_orig

## Explore SOCIB profiles

In [ ]:
z = xr.load_dataset("/home/sam_woodman_noaa_gov/depfrbyrd_amlr03_sgg3_L1_2023-11-27_data_rt.nc")
z

In [ ]:
# pgutils.get_profiles_new(x, filt_time=20)
p1, p2, p_opt = utils.findProfiles(
        z.time.values,
        z.depth.values,
        stall=20,
        # shake=200, 
        # interrupt = 600,
        # inversion = 10
    )

# orig = ["profile_index_orig", "profile_direction_orig"]
# x = x_orig.rename_vars({"profile_index": orig[0], "profile_direction": orig[1]})
z["profile_index_new"] = ('time', p1, {})
z["profile_direction_new"] = ('time', p2, {})
# x = utils.data_var_reorder(x, (vars_keep + orig))
z

In [ ]:
import matplotlib.pyplot as plt
depth = np.array([4, 4, 3, 2, 3, 4, 4, 5, 6, 6, 6, 5, 4, 4, 5, 3, 2, 3, 1, 1, 0, 4, 4])
x = np.arange(0, len(depth))

profile_index, profile_direction, prof_opt = utils.findProfiles(x, depth)
# %    figure
# %    subplot(3, 1, 1, 'XGrid','on','YGrid','on', 'NextPlot', 'add')
# %    stairs(profile_direction, '-g')
# %    subplot(3, 1, 2, 'XGrid','on','YGrid','on', 'NextPlot', 'add')
# %    plot(depth, '-db')
# %    subplot(3, 1, 3, 'XGrid','on','YGrid','on', 'NextPlot', 'add')
# %    stairs(profile_index, '-r')
# %    [profile_index, profile_direction] = findProfiles(depth, 'stall', 1.5)
# %    stairs(profile_index, '-c')
# %    [profile_index, profile_direction] = ...
# %       findProfiles(depth, 'stall', 1.5, 'inversion', 1.5, 'interrupt', inf)
# %    stairs(profile_index, '-m')

# Plotting
fig, axs = plt.subplots(3, 1, figsize=(10, 8), sharex=True)
axs[0].grid(True)
axs[0].stairs(profile_direction, color='g')
axs[0].set_title('Profile Direction')

axs[1].grid(True)
axs[1].plot(depth, '-db')
axs[1].set_title('Depth')
axs[1].invert_yaxis()

axs[2].grid(True)
axs[2].stairs(profile_index, color='r')
axs[2].set_title('Profile Index')

# Second call with stall parameter
profile_index, profile_direction = utils.findProfiles(x, depth, stall=1.5)
axs[2].stairs(profile_index, color='c', label='stall=1.5')

# Third call with more parameters
profile_index, profile_direction = utils.findProfiles(
    x, depth, stall=1.5, inversion=1.5, interrupt=np.inf)
axs[2].stairs(profile_index, color='m', label='stall=1.5, inversion=1.5, interrupt=inf')

axs[2].legend()
plt.tight_layout()
plt.show()